version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: renttrack_postgres
    restart: always
    environment:
      POSTGRES_USER: renttrack_user
      POSTGRES_PASSWORD: renttrack_secret_password
      POSTGRES_DB: renttrack_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
